const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const model = vm.runInThisContext(fs.readFileSync(require('node:path').join(__dirname, '../DenModel.js'), 'utf8') + '\n({tuckWidget})');
const c = {bar:{layout:{left:[],center:[],right:[{id:'so.den',widgets:['old']},{id:'new',setting:42}]}},plugins:[]};
assert.equal(model.tuckWidget(c,'so.den','new'),true);
assert.deepEqual(c.bar.layout.right,[{id:'so.den',widgets:['old','new']}]);
assert.deepEqual(c.plugins,[{id:'new',setting:42}]);
const once=JSON.stringify(c);
model.tuckWidget(c,'so.den','new');
assert.equal(JSON.stringify(c),once);
c.plugins.push({id:'orphan',setting:7});
assert.equal(model.tuckWidget(c,'so.den','orphan'),true);
assert.equal(c.bar.layout.right[0].widgets.includes('orphan'),true);
const saved=JSON.stringify(c);
assert.equal(model.tuckWidget(c,'missing','orphan'),false);
assert.equal(model.tuckWidget(c,'so.den','unknown'),false);
assert.equal(JSON.stringify(c),saved);
console.log('PASS: atomic tuck, settings, idempotence, interrupted-tuck recovery, missing-entry guards');
